name: flutter_whale
description: Project base component.
version: 1.1.8
repository: https://github.com/yalong0521/flutter_whale

environment:
  sdk: '>=2.18.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  dio: ^5.3.3
  path_provider: ^2.1.3
  path: ^1.9.0
  synchronized: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
